{% set name = "axial-positional-embedding" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/axial_positional_embedding-{{ version }}.tar.gz
  sha256: 2f9fe133b454474976db2b8481b0872637f9ff144d205246f05ddd19bd8ff8f3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pytorch

test:
  imports:
    - axial_positional_embedding
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lucidrains/axial-positional-embedding
  summary: Axial Positional Embedding
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - maresb
