{% set name = "axial-positional-embedding" %}
{% set version = "0.3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/axial_positional_embedding-{{ version }}.tar.gz
  sha256: 8c4ca5e45aa0da3c2c0b6cb2fa2a310cc278125c17701497a2e835bfaf3c0ad1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - einops >=0.8.0
    - pytorch >=2.0

test:
  imports:
    - axial_positional_embedding
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lucidrains/axial-positional-embedding
  summary: Axial Positional Embedding
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - maresb
