{% set name = "axial-positional-embedding" %}
{% set version = "0.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/axial_positional_embedding-{{ version }}.tar.gz
  sha256: 2f8d8ddf36c68a12e35cec2513af477aaff8b67a890db9e340f2e609664c72de

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - einops >=0.8.0
    - pytorch >=2.0

test:
  imports:
    - axial_positional_embedding
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lucidrains/axial-positional-embedding
  summary: Axial Positional Embedding
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - maresb
